title: My Github Page using Minima and Jekyll
author: Arihant416
email: arihantjain416@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a sample static site to illustrate Github Pages and theme minima where Jekyll works behind the scenes.

# social links
twitter_username: Arihant2302 # DO NOT include the @ character, or else the build will fail!
github_username:  Arihant416 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
